apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collectorctrl-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collectorctrl-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "collectorctrl-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "collectorctrl-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "collectorctrl-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
          env:
            - name: OPAMP_SERVER
              value: {{ .Values.opamp.server | quote }}
            {{- if .Values.opamp.existingSecret }}
            - name: OPAMP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.opamp.existingSecret }}
                  key: secret-key
            {{- else if .Values.opamp.secretKey }}
            - name: OPAMP_SECRET_KEY
              value: {{ .Values.opamp.secretKey | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
